Add signing parameters to cfn template
buildkite/elastic-ci-stack-for-aws pull request #1263
Opened 2023-11-20 03:42 UTC by moskyb

2023-11-21 01:09 UTC, triarius reviewed
Thanks for doing the heave lifting here 🙇‍♂️

Do we actually need to upload the template to S3? Did you try writing it to a file and using the `file://` url instead?

Ok, I tried it, and it did not work either, but it might be worth mentioning that neither `--template-body` nor `--template-file file://` work in the PR description or in some comments.

2023-11-21 03:08 UTC, moskyb commented on .buildkite/steps/launch.sh
> +aws --no-cli-pager cloudformation validate-template \
ah, i just copied this straight from the makefile - it'll be running on CI instances, so maybe we wanna be double sure?

2025-09-10 21:34 UTC, tomowatt requested changes

2025-09-10 21:34 UTC, tomowatt commented on templates/aws-stack.yml
> +    Default: ""
Per [docs](https://buildkite.com/docs/agent/v3/cli-start#verification-failure-behavior), the only valid options are block and warn, with block being the default.
So shouldn't the CF Parameters also reflect this?

2025-10-01 17:54 UTC, tomowatt approved these changes

2025-10-07 23:25 UTC, merged