Add changelog for v5.8.0
buildkite/elastic-ci-stack-for-aws pull request #991
Opened 2022-03-01 02:15 UTC by moskyb

2022-03-01 02:51 UTC, pda commented on CHANGELOG.md
> +### Added
Previous entries put a blank line between the heading and the lists.
I don't know if there's markdown renderers that care about the difference, though.

2022-03-01 02:51 UTC, pda commented on CHANGELOG.md
> +- Allow Docker address pool customisation [#968](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/968) (@ouranos)
This one ended up being more like:

> Smaller docker networks allow 16x as many docker-compose networks

We removed the customisation aspect mentioned in the PR title.

2022-03-01 02:51 UTC, pda commented on CHANGELOG.md
> +- Recognise c7g instances as ARM [#979](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/979) (@pda)
These two could be rolled into one, with credit to @toothbrush and @yob

2022-03-01 02:51 UTC, pda commented on CHANGELOG.md
> +- fix: force symlink override if exists [#970](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/970) (@chefsale)
This one could be:

> Overwrite /usr/bin/buildkite-agent symlink if it already exists

2022-03-08 03:02 UTC, eleanorakh requested changes

2022-03-08 04:45 UTC, eleanorakh approved these changes
I've also reviewed pauls suggestion above, I think that #968 is fine.

Other suggestion non-blocking 💃

2022-03-20 21:52 UTC, moskyb commented on CHANGELOG.md
> +- Smaller docker networks allow 16x as many docker-compose networks [#968](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/968) (@ouranos)
i think that part of the PR never went through, all we did is customise the docker network sizes, and we didn't end up adding the flag. i've updated this summary to be a little clearer though, regardless

2022-03-28 02:04 UTC, pda approved these changes

2022-03-28 02:37 UTC, merged